# Generated by Django 6.0.3 on 2026-04-07 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=50)),
                ('genre', models.TextField(choices=[('aventure', 'Aventure'), ('biographie', 'Biographie'), ('fantastique', 'Fantastique'), ('histoire', 'Histoire'), ('horreur', 'Horreur'), ('policier', 'Policier'), ('roman', 'Roman'), ('science_fiction', 'Science-Fiction'), ('thriller', 'Thriller')], max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('date_de_publication', models.DateField()),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
